---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: parakeet
# description will be included in the image's metadata
description: silverblue + niri for aarch64 uefi

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      copr:
        - avengemedia/danklinux
    install:
      packages:
        - brightnessctl
        - btop
        - cava
        - chezmoi
        - cliphist
        - ddcutil
        - dialog
        - eog
        - fastfetch
        - fira-code-fonts
        - firefox
        - freerdp
        - gnome-calculator
        - gnome-clocks
        - gparted
        - ImageMagick
        - jetbrainsmono-nerd-fonts
        - kitty
        - libvirt
        - mediawriter
        - mpv
        - niri
        - nmap-ncat
        - noctalia-shell
        - papers
        - python3-pip
        - qemu
        - qt6ct
        - screen
        - swayidle
        - tailscale
        - telnet
        - vim
        - virt-manager
        - wayvnc
        - wlsunset
        - xfce-polkit
        - yazi
        - zed

    remove:
      packages:
        - htop
        - gnome-software
        - gnome-system-monitor

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.ranfdev.DistroShelf
          - io.github.flattool.Ignition
          - io.github.kolunmi.Bazaar
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.remmina.Remmina
          - page.codeberg.libre_menu_editor.LibreMenuEditor

  - type: signing

  - type: systemd
    system:
      enabled:
        - tailscaled
        - libvirtd
        - sshd

  - type: gnome-extensions
    install:
      - 6670 #Bluetooth Battery Meter
      - 3193 #Blur my Shell
      - 615  #AppIndicator and KStatusNotifierItem Support
      - 517  #Caffeine
      - 744  #Hide Activities Button
      - 4099 #No overview at start-up
      - 5964 #Quick Settings Audio Devices Hider

  - type: kargs
    kargs:
      - split_lock_detect=off
